# Generated by Django 2.2.12 on 2021-07-16 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationsModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteLocations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image_src', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.LocationsModel')),
            ],
        ),
    ]
