# Generated by Django 2.2.12 on 2021-07-25 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20210716_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteImage',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('secret', models.CharField(max_length=256)),
                ('farm', models.CharField(max_length=256)),
                ('server', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'FavouriteImages',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'Locations',
            },
        ),
        migrations.AddField(
            model_name='favouriteimage',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location'),
        ),
    ]
