# Generated by Django 2.2.12 on 2021-07-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_auto_20210725_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouriteimage',
            name='title',
            field=models.CharField(default='Default_Title', max_length=256),
        ),
    ]
