# Generated by Django 2.2.12 on 2021-07-25 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_auto_20210725_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouriteimage',
            name='location',
        ),
        
    ]
