# Generated by Django 2.2.12 on 2021-07-25 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20210725_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.FavouriteImage')),
            ],
        ),
    ]
