# Generated by Django 2.2.12 on 2021-07-25 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_auto_20210725_0617'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='note',
            table='Notes',
        ),
    ]
