# Generated by Django 2.2.12 on 2021-07-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_auto_20210725_0620'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavouriteLocations',
        ),
        migrations.DeleteModel(
            name='LocationsModel',
        ),
    ]
